-- 회비 관리 정보 테이블
CREATE TABLE Fee(
	F_ID NUMBER NOT NULL PRIMARY KEY,
	F_TITLE VARCHAR(50) NOT NULL,
	F_DATE DATE NOT NULL
)

CREATE SEQUENCE fee_id
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

SELECT F_ID, F_TITLE, F_DATE FROM Fee;
INSERT INTO Fee(F_ID, F_TITLE, F_DATE) VALUES (fee_id.NEXTVAL, ?, ?);
UPDATE Fee SET F_TITLE=?, F_DATE=? WHERE F_ID=?;
DELETE FROM Fee WHERE F_ID=?;



-- 회비 관리 명단 정보 테이블
CREATE TABLE FeeMember(
	FM_ID NUMBER NOT NULL PRIMARY KEY,
	FM_M_INDEX NUMBER NOT NULL,
	FM_MT_ID NUMBER NOT NULL,
	FM_FEE NUMBER NOT NULL,
	FM_NOTE VARCHAR(30)
)

CREATE SEQUENCE feemember_id
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

ALTER TABLE FeeMember ADD FOREIGN KEY(FM_M_INDEX) REFERENCES Member(M_INDEX);
ALTER TABLE FeeMember ADD FOREIGN KEY(FM_MT_ID) REFERENCES Meeting(MT_ID);

SELECT FM_ID, FM_M_INDEX, FM_MT_ID, FM_FEE, FM_NOTE FROM FeeMember;
INSERT INTO FeeMember(FM_ID, FM_M_INDEX, FM_MT_ID, FM_FEE, FM_NOTE) VALUES (feemember_id.NEXTVAL, ?, ?, ?, ?);
UPDATE FeeMember SET FM_M_INDEX=?, FM_MT_ID=?, FM_FEE=?, FM_NOTE=? WHERE FM_ID=?;
DELETE FROM FeeMember WHERE FM_ID=?;



-- 회비관리 지출내역 정보 테이블
CREATE TABLE FeeExpense(
	FE_ID NUMBER NOT NULL PRIMARY KEY,
	FE_MT_ID NUMBER NOT NULL,
	FE_EXPENSE VARCHAR(30) NOT NULL,
	FE_EXPENSEFEE NUMBER NOT NULL
)

CREATE SEQUENCE feeexpense_id
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

ALTER TABLE FeeExpense ADD FOREIGN KEY(FE_MT_ID) REFERENCES Meeting(MT_ID);

SELECT FE_ID, FE_F_ID, FE_EXPENSE, FE_EXPENSEFEE FROM FeeExpense;
INSERT INTO FeeExpense(FE_ID, FE_MT_ID, FE_EXPENSE, FE_EXPENSEFEE) VALUES (?, ?, ?, ?);
UPDATE FeeExpense SET FE_MT_ID=?, FE_EXPENSE=?, FE_EXPENSEFEE=? WHERE FE_ID=?;
DELETE FROM FeeExpense WHERE FE_ID=?;


-- 테이블 전체 보기.
select * from tab;
